version: '3.8'
services:
  backend:
    container_name: kaye_api
    build: .
    tty: true
    env_file: .env
    environment:
      TZ: Asia/Tokyo
      PROJECT_ID: $PROJECT_ID
      CLIENT_EMAIL: $CLIENT_EMAIL
      PRIVATE_KEY: $PRIVATE_KEY
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /kaye_api
networks:
  default:
    name: kaye_api
